name: Update Steam Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: Nicconike/Steam-Stats@main
        with:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
