name: Steam Stats

on:
  push:
    branches: master
    schedule:
      # Runs every Monday at 12AM IST (UTC+5:30)
      - cron: "30 18 * * 0"
    workflow_dispatch:

jobs:
  steam-stats:
    name: Steam Stats
    runs-on: ubuntu-latest
    steps:
      - uses: nicconike/steam-stats@master
        with:
          STEAM_API_KEY: ${{ secrets.1AAB82D78418484AB58DEE0A9C3041F6 }} # Created Steam API key env var
          STEAM_ID: ${{ vars.STEAM_0:1:151744454 }} # Steam ID env var
          STEAM_CUSTOM_ID: ${{ vars.https://steamcommunity.com/id/AndryGoldmann/ }} # Custom ID env var
          WORKSHOP_STATS: True # Optional
          LOG_SCALE: True # Optional
