name: Update XBL Stats

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Grants GITHUB_TOKEN write access for pushes

jobs:
  build:
    name: Update-XBL-stats
    runs-on: ubuntu-latest
    env:
      XBL_API_KEY: ${{ secrets.XBL_API_KEY }}
      XBL_XUID: ${{ secrets.XBL_XUID }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Build combined updater
        run: |-
          cat > main.go << 'EOF'
          [Paste the entire combined main.go code here—replace [Paste...] with the code above]
          EOF
          go mod init combined-updater
          go get github.com/YouEclipse/steam-box/pkg/steambox
          go mod tidy
          go build -o updater main.go
          rm -f main.go go.mod go.sum
      - name: Update README with stats
        run: ./updater
      - name: Commit and push
        run: |-
          git config --global user.email "bot@github.com" && git config --global user.name "Stats-Bot"
          git config --global pull.rebase false
          git diff
          git add README.md && git commit -m "Update XBL stats" || exit 0
          git pull && git push
